name: TEST-CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: TEST-CD
    steps:
      - uses: EPFL-ENAC/epfl-enac-deploy-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
