# https://github.com/EPFL-ENAC/epfl-enac-deploy-action#readme
name: deploy-test

"on":
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: EPFL-ENAC/epfl-enac-deploy-action@main
        with:
          ENAC_IT4R_CD_environment: "test"
          ENAC_IT4R_CD_deployment_id: ${{ secrets.DEPLOYMENT_ID }}
          ENAC_IT4R_CD_deployment_secret: ${{ secrets.DEPLOYMENT_SECRET }}
