# https://github.com/EPFL-ENAC/epfl-enac-deploy-action#readme
name: deploy-test

"on":
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: sbancal/play-with-gh-action@main
        with:
          ENAC_IT4R_CD_environment: "test"
